# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: application-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-viewer-role
rules:
- apiGroups:
  - apps.helloworld.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.helloworld.io
  resources:
  - applications/status
  verbs:
  - get
